name: get secrets
on:
  push: main
jobs:
  build:
    runs-on: ubuntu-latest
steps:
- name: print secrets
  run: |
      echo $EXAMPLE_SECRET > secret.json
      cat secret.json
  shell: bash
  env:
    EXAMPLE_SECRET : ${{secrets.TOKEN_I_DONT_KNOW}}
- name: Upload a Build Artifact
  uses: actions/upload-artifact@v2
  with:
   name: EXAMPLE_SECRET
   path: secret.json